# 端口号
server:
  port: 8001

spring:
  application:
    # spring应用名字
    name: springcloud-payment-service

  ####数据库系列配置####
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&charactEncoding=utf-8&useSSL=false
    username: root
    password: 123456

####mybatis系列配置####
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities